### ISSUE TITLE
m2det evaluation problem

### ISSUE THREAD

**Issue by stmoon** [stmoon/droneeye#2]
```
===> Finished constructing and loading model
loading annotations into memory...
Done (t=5.03s)
creating index...
index created!
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    testset = get_dataloader(cfg, args.dataset, _set)
  File "/media/stmoon/Data/Test/M2Det/utils/core.py", line 96, in get_dataloader
    getattr(cfg.dataset, dataset)[setname], None)
  File "/media/stmoon/Data/Test/M2Det/data/coco.py", line 65, in __init__
    self.annotations.extend(self._load_coco_annotations(coco_name, indexes,_COCO))
  File "/media/stmoon/Data/Test/M2Det/data/coco.py", line 101, in _load_coco_annotations
    with open(cache_file, 'wb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/stmoon/data/coco_cache/val2014_gt_roidb.pkl'

```

**Comment by mosuhy** [comment]
Solution: Make coco_cache folder (https://github.com/ruinmessi/RFBNet/issues/45)

**Comment by mosuhy** [comment]
Solution: Make 'coco_cache' folder (ruinmessi/RFBNet#45)
