### ISSUE TITLE
m2det training problem

### ISSUE THREAD

**Issue by stmoon** [stmoon/droneeye#3]
```bash
(env) stmoon@DeepServer2:/media/stmoon/Data/Test/M2Det$ CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py -c=configs/m2det512_vgg.py --ngpu 4 -t True
----------------------------------------------------------------------
|                       M2Det Training Program                       |
----------------------------------------------------------------------
===> Constructing M2Det model
Loading base network...
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    init_net(net, cfg, args.resume_net) # init the network with pretrained weights or resumed weights
  File "/media/stmoon/Data/Test/M2Det/utils/core.py", line 39, in init_net
    net.init_model(cfg.model.pretrained)
  File "/media/stmoon/Data/Test/M2Det/m2det.py", line 155, in init_model
    self.base.load_state_dict(base_weights)
  File "/media/stmoon/Data/Test/M2Det/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModuleList:
	Missing key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "5.weight", "5.bias", "7.weight", "7.bias", "10.weight", "10.bias", "12.weight", "12.bias", "14.weight", "14.bias", "17.weight", "17.bias", "19.weight", "19.bias", "21.weight", "21.bias", "24.weight", "24.bias", "26.weight", "26.bias", "28.weight", "28.bias", "31.weight", "31.bias", "33.weight", "33.bias". 

```

**Comment by mosuhy** [comment]
Possible solution: https://github.com/qijiezhao/M2Det/issues/51
